# Generated by Django 3.0.6 on 2020-05-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0003_auto_20200522_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('affiliationid', models.IntegerField(max_length=11)),
                ('affiliationname', models.CharField(max_length=255)),
                ('conutry', models.CharField(max_length=255)),
                ('c_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['username', 'c_time'],
            },
        ),
        migrations.CreateModel(
            name='AuthorCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('authorid', models.IntegerField(max_length=11)),
                ('authorname', models.CharField(max_length=255)),
                ('authoraffiliation', models.CharField(max_length=255)),
                ('c_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['username', 'c_time'],
            },
        ),
        migrations.CreateModel(
            name='PaperCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('paperid', models.IntegerField(max_length=11)),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField(max_length=11)),
                ('authors', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('c_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['username', 'c_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['c_time']},
        ),
    ]
