# Generated by Django 3.0.6 on 2020-05-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0006_ampaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmAffiliation',
            fields=[
                ('affiliation_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_cn', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500)),
                ('wiki_page', models.CharField(max_length=500)),
                ('country_id', models.IntegerField()),
                ('grid_id', models.CharField(max_length=100)),
                ('introduction', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
                ('wikidata', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'am_affiliation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmAuthor',
            fields=[
                ('author_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('normalizedname', models.CharField(db_column='NormalizedName', max_length=255)),
                ('name_cn', models.CharField(max_length=500)),
                ('last_known_affiliation_id', models.PositiveIntegerField()),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'am_author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmCountry',
            fields=[
                ('country_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('name_cn', models.CharField(max_length=255)),
                ('official_name', models.CharField(max_length=255)),
                ('alpha2', models.CharField(max_length=2)),
                ('alpha3', models.CharField(max_length=3)),
                ('numeric', models.CharField(max_length=3)),
                ('independence', models.IntegerField()),
                ('continent', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'am_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmPaperAbstract',
            fields=[
                ('paper_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('abstract', models.TextField()),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'am_paper_abstract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmPaperAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.PositiveIntegerField()),
                ('author_id', models.PositiveIntegerField()),
                ('affiliation_id', models.PositiveIntegerField()),
                ('sequence', models.PositiveSmallIntegerField()),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'am_paper_author',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='affiliationcollect',
            name='introduction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
