# Generated by Django 3.0.6 on 2020-05-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0012_auto_20200528_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorcollectfield',
            old_name='filecount',
            new_name='fieldcount',
        ),
        migrations.RenameField(
            model_name='papercollectfield',
            old_name='filecount',
            new_name='fieldcount',
        ),
    ]
