# Generated by Django 3.0.6 on 2020-05-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0014_auto_20200528_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorcollectfield',
            options={'ordering': ['username', 'fieldcount']},
        ),
        migrations.AlterModelOptions(
            name='papercollectfield',
            options={'ordering': ['username', 'fieldcount']},
        ),
    ]
