# Generated by Django 3.0.6 on 2020-05-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0015_auto_20200528_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmField',
            fields=[
                ('field_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_cn', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=200)),
                ('level', models.PositiveIntegerField()),
                ('wiki_page', models.CharField(max_length=500)),
                ('introduction', models.TextField()),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
                ('wikidata', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'am_field',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='authorcollectfield',
            options={'ordering': ['username', '-fieldcount']},
        ),
        migrations.AlterModelOptions(
            name='papercollectfield',
            options={'ordering': ['username', '-fieldcount']},
        ),
    ]
