# Generated by Django 3.0.6 on 2020-05-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0016_auto_20200528_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorcollectfield',
            name='fieldname',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papercollectfield',
            name='fieldname',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
