# Generated by Django 3.0.6 on 2020-05-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0017_auto_20200528_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedAffiliations',
            fields=[
                ('affiliation_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_cn', models.CharField(max_length=200)),
                ('introduction', models.TextField()),
            ],
            options={
                'ordering': ['affiliation_id'],
            },
        ),
    ]
