# Generated by Django 3.0.6 on 2020-05-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0018_parsedaffiliations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsedaffiliations',
            options={'ordering': ['affiliationid']},
        ),
        migrations.RenameField(
            model_name='parsedaffiliations',
            old_name='affiliation_id',
            new_name='affiliationid',
        ),
        migrations.RenameField(
            model_name='parsedaffiliations',
            old_name='name_cn',
            new_name='namecn',
        ),
        migrations.AddField(
            model_name='parsedaffiliations',
            name='country_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
