# Generated by Django 3.0.6 on 2020-05-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0020_auto_20200530_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedaffiliations',
            name='countryid',
        ),
        migrations.RemoveField(
            model_name='parsedaffiliations',
            name='namecn',
        ),
        migrations.AlterField(
            model_name='parsedaffiliations',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
