# Generated by Django 3.0.6 on 2020-05-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0022_auto_20200530_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedaffiliations',
            name='shortname',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
