# Generated by Django 3.0.6 on 2020-05-30 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0024_recommendresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendresult',
            old_name='needupdata',
            new_name='needupdate',
        ),
    ]
