# Generated by Django 3.0.6 on 2020-05-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0008_auto_20200524_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorcollect',
            name='url',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
