# Generated by Django 3.0.6 on 2020-05-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0009_authorcollect_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorcollect',
            name='url',
        ),
        migrations.AddField(
            model_name='affiliationcollect',
            name='url',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
