# Generated by Django 3.0.6 on 2020-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0011_cuauthorfield_cuparentfield_cuteauthorfield_cuteparentfield_ecnuauthorfield_ecnuparentfield_fudanaut'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmPaperField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('keyword', models.CharField(max_length=255)),
                ('field_id', models.PositiveIntegerField()),
                ('created_at', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'am_paper_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorCollectField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('filedid', models.PositiveIntegerField()),
                ('filecount', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='PaperCollectField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('filedid', models.PositiveIntegerField()),
                ('filecount', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.AlterField(
            model_name='affiliationcollect',
            name='affiliationid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='authorcollect',
            name='authorid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='papercollect',
            name='paperid',
            field=models.PositiveIntegerField(),
        ),
    ]
