# Generated by Django 3.0.6 on 2020-05-30 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0019_auto_20200530_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsedaffiliations',
            old_name='country_id',
            new_name='countryid',
        ),
    ]
