# Generated by Django 3.0.6 on 2020-05-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommandSys', '0021_auto_20200530_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedaffiliations',
            name='countryname',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsedaffiliations',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
